### ISSUE TITLE
Ein paar kurze fragen

### ISSUE THREAD

**Issue by LokiMidgard** [FSI-HochschuleTrier/satzung#2]
Gilt für die unter §6 Absatz 2 erwähnte außerordentliche Vollversammlung auch §5 Absatz 3?
In diesem Fall müsste die außerordentliche Versammlung exakt in zwei Wochen stattfinden (mindestens und maximal zwei Wochen)

§9 Absatz 2:
Wie stellt der rat dies sicher? geht es da nur um Werbung machen für die Wahl zum stupa?

§10 Absatz 1:
Sollte es vielleicht "...setzt sich aus <maximal> 15, mindestens..."? Ich habe immer das Gefühl bei rechtstexten muss man jedes Wort auf die Goldwaage legen, und für mich würde es sich anhören, also ob man alles daran setzen müsste die 15 voll zu bekommen.

§12 Absatz 4:
Dieser und Spätere sprechen von Vorsitzenden, aber in Absatz 1 werden nur Sprecher und Finanzreferent bzw. deren Stellvertreter definiert.

**Comment by Berling** [comment]
Für §6 Abs. 2 gilt §5 Abs. 3 nicht, andernfalls hätte es dazu einen Verweis gegeben. Eine außerordentliche Vollversammlung kann ja nur einberufen werden wenn bereits eine ordentliche Vollversammlung einberufen wurde, aber zu wenig Mitglieder anwesend waren. Damit sind die TOPs und die Tatsache das es eine Vollversammlung gibt bereits bekannt. Allerdings sollte in §6 Abs. 2 noch darauf hingewiesen werden, das auch die Bekanntmachung der außerordentliche Vollversammlung möglichst viele Studierende erreichen soll.

§9 Abs. 2 wurde so aus der Satzung der Studierendenschaft der Hochschule Trier übernommen. Wie der Fachschaftsrat dies sicher stellt ist ihm überlassen. Ich denke auch nicht das es sinnvoll ist Methoden festzuschreiben. Ich bin kein Experte im Leute werben und maße es mir nicht an dann Maßnahmen für §9 Abs. 2 festzusetzen.

Ich verstehe die Frage zu §10 Abs. 1 nicht so ganz. Deine Formulierung steht doch genau so drin.

§12 Absatz 4 ff. sind Übertragungsfehler aus den entsprechenden Paragraphen des AStA-Vorstands. Das korrigiere ich.

**Comment by Berling** [comment]
Vorsitzende/r wurde jetzt durch Sprecher/in ersetzt

**Comment by LokiMidgard** [comment]
Die Frage die du Nicht verstehst, ist auch falsch Formuliert, also kein wunder.
Ich wollte ein maximal einfügen. Also "...setzt sich aus maximal 15, mindestens..."
